version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: user-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auto_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: user-mongodb
    ports:
      - "27019:27017"  # Different port to avoid conflict with vehicle service
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: userprofiledb
    volumes:
      - mongodb_data:/data/db

  pgadmin:
    image: dpage/pgadmin4
    container_name: user-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  mongo-express:
    image: mongo-express:latest
    container_name: user-mongo-express
    ports:
      - "27020:8081"  # Different port to avoid conflict
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_MONGODB_URL: mongodb://root:rootpassword@mongodb:27017/
    depends_on:
      - mongodb

volumes:
  postgres_data:
  mongodb_data: