version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: vehicle-mongodb
    ports:
      - "27017:27017"  # Expose to host machine
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: vehicledb

  mongo-express:  # Optional UI
    image: mongo-express:latest
    ports:
      - "27018:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_MONGODB_URL: mongodb://root:rootpassword@mongodb:27017/
    depends_on:
      - mongodb